name: Generate Test Cases

on:
  push:
    branches:
      - main

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install litellm
      
      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          export PATH="/root/.ollama/bin:$PATH"
          ollama pull llama2

      - name: Start Ollama Service
        run: |
          ollama serve --address 0.0.0.0:11434 &
          sleep 5

      - name: Wait for Ollama to Start
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:11434/v1/models && break
            echo "Waiting for Ollama to be ready..."
            sleep 2
          done

      - name: Check Ollama Status
        run: |
          sudo systemctl status ollama.service

      - name: Generate Tests
        run: python generate_tests.py

      - name: Check if tests were generated
        run: ls -R src/test || echo "⚠️ No test cases generated"

      - name: Commit and push generated tests (if any)
        if: success()
        run: |
          if [ -n "$(ls -A src/test/ 2>/dev/null)" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add src/test/*
            git commit -m "🤖 Auto-generated test cases"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/shadabmalikshah/openAI_testCase_generation.git
          else
            echo "⚠️ No new test cases to commit"
