name: Generate Test Cases

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai  # Install OpenAI SDK

      - name: Verify OpenAI API Key
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "❌ ERROR: OPENAI_API_KEY is missing!"
            exit 1
          else
            echo "✅ OpenAI API Key is set."
          fi

      - name: Run Test Case Generation Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_tests.py

      - name: Debug Generated Files
        run: ls -R openAI_testCase_generation/src || echo "No test cases generated"

      - name: Upload Generated Test Cases as Artifact
        if: success()
        uses: actions/upload-artifact@4
        with:
          name: generated-test-cases
          path: openAI_testCase_generation/src/test/

      - name: Commit and Push Changes
        run: |
          if [ -n "$(ls -A openAI_testCase_generation/src/test/ 2>/dev/null)" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add openAI_testCase_generation/src/test/*
            git commit -m "🤖 Auto-generated test cases"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/shadabmalikshah/openAI_testCase_generation.git
          else
            echo "⚠️ No new test cases to commit"
          fi
