name: Generate Test Cases

on:
  push:
    branches:
      - main

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      - name: Start Ollama
        run: |
          ollama serve &
          sleep 5

      - name: Pull Llama3 model for Ollama
        run: |
          ollama pull llama3

      - name: Generate test cases
        run: python generate_tests.py

      - name: Check if tests are generated
        run: |
          if [ -n "$(ls -A src/test/ 2>/dev/null)" ]; then
            echo "✅ Test cases generated."
          else
            echo "⚠️ No test cases generated."
          fi

      - name: Commit and push changes
        if: success()
        run: |
          if [ -n "$(ls -A src/test/ 2>/dev/null)" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add src/test/*
            git commit -m "🤖 Auto-generated test cases"
            git push https://github.com/shadabmalikshah/openAI_testCase_generation.git
          else
            echo "⚠️ No new test cases to commit"
          fi
