name: Generate Test Cases with OpenAI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install openai

      - name: Run Test Case Generation Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python openAI_testCase_generation/generate_tests.py

      - name: Ensure test directory exists
        run: mkdir -p openAI_testCase_generation/src/test

      - name: Commit and Push Generated Test Cases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          # Ensure test directory exists
          mkdir -p openAI_testCase_generation/src/test
          
          # Check if test files exist before adding
          if [ -n "$(ls -A openAI_testCase_generation/src/test/ 2>/dev/null)" ]; then
            git add openAI_testCase_generation/src/test/*
          else
            echo "No test files generated, skipping commit."
            exit 0
          fi
          
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
        
