name: Generate Test Cases

on:
  push:
    branches:
      - main  # Change if your default branch is different
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Ensure dependencies are installed
          pip install openai  # Ensure OpenAI library is installed

      - name: Verify Directory Structure
        run: ls -R  # Debugging step to check file paths

      - name: Run Test Case Generation Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python openAI_testCase_generation/generate_tests.py

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          # Check if test files were created/modified
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add openAI_testCase_generation/src/test/*
            git commit -m "🤖 Auto-generated test cases"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/shadabmalikshah/openAI_testCase_generation.git
          fi
