name: Generate  Test Cases

on:
  push:
    branches:
      - main

permissions:
  contents: write   # ✅ Grant write access to the repository

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # ✅ Use GitHub token for authentication

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests litellm

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      - name: Kill existing Ollama process (if any)
        run: |
          if lsof -i :11434 -t > /dev/null 2>&1; then
            echo "⚠️ Port 11434 is in use. Killing existing Ollama process..."
            kill -9 $(lsof -i :11434 -t)
          else
            echo "✅ Port 11434 is free."
          fi

      - name: Start Ollama
        run: |
          nohup ollama serve > ollama.log 2>&1 &
          sleep 5
          cat ollama.log

      - name: Pull Llama3 model for Ollama
        run: |
          ollama pull llama3

      - name: Generate test cases
        run: python generate_tests.py

      - name: Check if tests are generated
        run: |
          if [ -n "$(ls -A src/test/ 2>/dev/null)" ]; then
            echo "✅ Test cases generated."
          else
            echo "⚠️ No test cases generated."
          fi

      - name: Commit and push changes
        if: success()
        run: |
          if [ -n "$(ls -A src/test/ 2>/dev/null)" ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add src/test/*
            git commit -m "🤖 Auto-generated test cases"
            git push origin main
          else
            echo "⚠️ No new test cases to commit"
          fi
